name: search_party_migrations

services:
  team_player_profiles_migrations:
    container_name: team_player_profiles_migrations
    depends_on:
      team_player_profiles_db:
        condition: service_healthy
    build: 
      context: ../../TeamPlayerProfiles
      dockerfile: migrate.Dockerfile
    ports: 
      - "8080:8080" 
      - "8081:8081" 
    environment:
      CONTAINER: true
      DATABASE_HOSTNAME: team_player_profiles_db
      DATABASE_PORT: 5432
      DATABASE_NAME: team_player_profiles
      DATABASE_USER: ${POSTGRES__USER}
      DATABASE_PASSWORD: ${POSTGRES__PASSWORD}
      TEAM_PLAYER_PROFILES__ADD_MIGRATION: ${TEAM_PLAYER_PROFILES__ADD_MIGRATION}
      TEAM_PLAYER_PROFILES__APPLY_MIGRATION: ${TEAM_PLAYER_PROFILES__APPLY_MIGRATION}
      TEAM_PLAYER_PROFILES__MIGRATION_NAME: ${TEAM_PLAYER_PROFILES__MIGRATION_NAME}
      TEAM_PLAYER_PROFILES__STARTUP_PROJECT_NAME: ${TEAM_PLAYER_PROFILES__STARTUP_PROJECT_NAME}
      TEAM_PLAYER_PROFILES__CONTEXT_PROJECT_NAME: ${TEAM_PLAYER_PROFILES__CONTEXT_PROJECT_NAME}

  team_player_profiles_db:

    container_name: team_player_profiles_db
    image: postgres:latest
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: team_player_profiles
      POSTGRES_USER: ${POSTGRES__USER}
      POSTGRES_PASSWORD: ${POSTGRES__PASSWORD}
    volumes: 
      - team_player_profiles_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES__USER} -d team_player_profiles"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s 

volumes:
  team_player_profiles_pg_data:
    name: "team_player_profiles_pg_data"

