name: search_party

services:
  team_player_profiles_webapi:
    container_name: team_player_profiles_webapi
    depends_on:
      team_player_profiles_db:
        condition: service_healthy
    build: 
      context: ../../TeamPlayerProfiles
      dockerfile: build.Dockerfile
      args:
        BUILD_CONFIGURATION: ${BUILD_CONFIGURATION}
    ports: 
      - "8080:8080" 
      - "8081:8081" 
    environment:
      CONTAINER: true
      DATABASE_HOSTNAME: team_player_profiles_db
      DATABASE_PORT: 5432
      DATABASE_NAME: team_player_profiles
      DATABASE_USER: ${POSTGRES__USER}
      DATABASE_PASSWORD: ${POSTGRES__PASSWORD}
      SEED_DATABASE: ${TEAM_PLAYER_PROFILES__SEED_DATABASE}

  team_player_profiles_db:
    container_name: team_player_profiles_db
    image: postgres:latest
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: team_player_profiles
      POSTGRES_USER: ${POSTGRES__USER}
      POSTGRES_PASSWORD: ${POSTGRES__PASSWORD}
    volumes: 
      - team_player_profiles_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES__USER} -d team_player_profiles"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s 

volumes:
  team_player_profiles_pg_data:
    name: "team_player_profiles_pg_data"
    external: true

