name: search_party

services:
  team_player_profiles_webapi:
    container_name: team_player_profiles_webapi
    depends_on:
      team_player_profiles_db:
        condition: service_healthy
    build: 
      context: ../../
      dockerfile: TeamPlayerProfiles/build.Dockerfile
      args:
        BUILD_CONFIGURATION: ${BUILD_CONFIGURATION}
    ports: 
      - "8080:8080" 
      - "8081:8081" 
    environment:
      DATABASE_HOSTNAME: team_player_profiles_db
      DATABASE_PORT: 5432
      DATABASE_NAME: team_player_profiles
      DATABASE_USER: ${POSTGRES__USER}
      DATABASE_PASSWORD: ${POSTGRES__PASSWORD}
      AUTHENTICATION_SERVICE_URL: ${AUTHENTICATION_SERVICE_URL}
      TEAM_PLAYER_PROFILES__SEED_DATABASE: ${TEAM_PLAYER_PROFILES__SEED_DATABASE}
      TOKEN_KEY: ${TOKEN_KEY}
  team_player_profiles_db:
    container_name: team_player_profiles_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: team_player_profiles
      POSTGRES_USER: ${POSTGRES__USER}
      POSTGRES_PASSWORD: ${POSTGRES__PASSWORD}
    volumes: 
      - team_player_profiles_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES__USER} -d team_player_profiles"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  user_info_webapi:
    container_name: user_info_webapi
    depends_on:
      user_info_db:
        condition: service_healthy
    build: 
      context: ../../
      dockerfile: UserInfo/build.Dockerfile
      args:
        BUILD_CONFIGURATION: ${BUILD_CONFIGURATION}
    ports: 
      - "8082:8080" 
      - "8083:8081" 
    environment:
      DATABASE_HOSTNAME: user_info_db
      DATABASE_PORT: 5432
      DATABASE_NAME: user_info
      DATABASE_USER: ${POSTGRES__USER}
      DATABASE_PASSWORD: ${POSTGRES__PASSWORD}
      USER_INFO__SEED_DATABASE: ${USER_INFO__SEED_DATABASE}
      TEAM_PLAYER_PROFILES_URL: ${TEAM_PLAYER_PROFILES_URL}
      AUTHENTICATION_SERVICE_URL: ${AUTHENTICATION_SERVICE_URL}
      TOKEN_KEY: ${TOKEN_KEY}
  user_info_db:
    container_name: user_info_db
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: user_info
      POSTGRES_USER: ${POSTGRES__USER}
      POSTGRES_PASSWORD: ${POSTGRES__PASSWORD}
    volumes: 
      - user_info_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES__USER} -d user_info"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  user_auth_webapi:
    container_name: user_auth_webapi
    depends_on:
      user_info_db:
        condition: service_healthy
    build: 
      context: ../../
      dockerfile: Auth/build.Dockerfile
      args:
        BUILD_CONFIGURATION: ${BUILD_CONFIGURATION}
    ports: 
      - "8084:8080" 
      - "8085:8081" 
    environment:
      DATABASE_HOSTNAME: user_auth_db
      DATABASE_PORT: 5432
      DATABASE_NAME: user_auth
      DATABASE_USER: ${POSTGRES__USER}
      DATABASE_PASSWORD: ${POSTGRES__PASSWORD}
      USER_AUTH__SEED_DATABASE: ${USER_AUTH__SEED_DATABASE}
      TOKEN_KEY: ${TOKEN_KEY}
      REFRESH_KEY: ${REFRESH_KEY}
  user_auth_db:
    container_name: user_auth_db
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: user_auth
      POSTGRES_USER: ${POSTGRES__USER}
      POSTGRES_PASSWORD: ${POSTGRES__PASSWORD}
    volumes: 
      - user_auth_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES__USER} -d user_auth"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  team_player_profiles_pg_data:
    name: "team_player_profiles_pg_data"
    external: true
  user_info_pg_data:
    name: "user_info_pg_data"
    external: true
  user_auth_pg_data:
    name: "user_auth_pg_data"
    external: true


